[supervisord]
nodaemon=true


[program:storage]
command = gunicorn --bind 127.0.0.1:5007 --workers 4 --threads 2 --access-logfile logs/access.log --error-logfile logs/error.log storage:app
autostart = true
autorestart = true
stopsignal = INT

[program:nginx]
command = nginx
user = root
autostart = true
autorestart = true

